config/routes.rb
Labparty::Application.routes.draw do
  resources :members

  resources :parties

  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure" => "sessions#failure"
  get "/logout" => "sessions#destroy", :as => :logout

  root :to => 'top#index'
  resources :home

end

app/models/member.rb
class Member < ActiveRecord::Base
	belongs_to :user
	belongs_to :party
	attr_accessible :attend, :user_id, :party_id
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /attends
  # GET /attends.json
  def index
    @members = Member.all
  end

  # GET /attends/1
  # GET /attends/1.json
  def show
  end

  # GET /attends/new
  def new
    # @party = Party.find(params[:id])
    @member = Member.new
  end

  # GET /attends/1/edit
  def edit
  end

  # POST /attends
  # POST /attends.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: '出欠情報を保存しました' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attends/1
  # PATCH/PUT /attends/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @attend, notice: 'Attend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to attends_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:attend, :user_id, :party_id)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this attend from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :出席しますか？ %>
    <%= f.select(:attend, {'◯' => 1, '△' => 2, '×' => 3}) %>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :party_id, :value => @party.id %>
  <div class="actions">
    <%= f.submit '登録' %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing attend</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing attends</h1>
<table>
  <thead>
    <tr>
      <th>Attend</th>
      <th>User</th>
      <th>Party</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attends.each do |attend| %>
    <tr>
      <td><%= attend.attend %></td>
      <td><%= attend.user_id %></td>
      <td><%= attend.party_id %></td>
      <td><%= link_to 'Show', attend %></td>
      <td><%= link_to 'Edit', edit_attend_path(attend) %></td>
      <td><%= link_to 'Destroy', attend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>出席確認</h1>
<%= render 'form' %>

<%= link_to 'Back', home_index_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>
<%= debug @member %>
<p>
  <strong>Member:</strong>
  <%= @member.attend %>
</p>

<p>
  <strong>User:</strong>
  <%= @member.user_id %>
</p>

<p>
  <strong>Party:</strong>
  <%= @member.party_id %>
</p>


<%= link_to 'ホーム', parties_path %>